### ISSUE TITLE
Problem with non translucent Navigation Bar

### ISSUE THREAD

**Issue by jchesne** [pixyzehn/PZPullToRefresh#1]
With non translucent navigation bar the script doesn't seem to work correctly. Bad positionning.

**Comment by pixyzehn** [comment]
@jchesne Thank for letting me know. I'll fix this bag soon.

**Comment by pixyzehn** [comment]
@jchesne 
I updated version 0.0.4 that fixed that bug. 
And you need to add the following code.

self.edgesForExtendedLayout = UIRectEdge.None

Please refer to the sample code.

**Comment by jchesne** [comment]
@pixyzehn Thanks, this is working perfectly !
