### ISSUE TITLE
Smoother reaload

### ISSUE THREAD

**Issue by jchesne** [pixyzehn/PZPullToRefresh#2]
As you can see, when you scroll down enough (50px or more i dont know exaclty) when you release the finger, the scrollView will "jump" and return to normal position, is it possible to fix this jumpy scroll ?

Try to use your script slowly, you will clearly see the jump effect, if you use it normaly with a big scroll down you will not see it, but can you do anything ?

**Comment by pixyzehn** [comment]
@jchesne 
Thank you for comment. I think that to fix is possible. I can see that jump effect.
I'll try to fix that bug soon.

**Comment by pixyzehn** [comment]
@jchesne 
Sorry for late. I changed smoother reload. This version is 0.0.6. Please confirm it on your project.

**Comment by jchesne** [comment]
Everytings works perfectly, big thanks !

**Comment by pixyzehn** [comment]
@jchesne
I'm glad to hear that. If you have any questions, feel free to contact me.
